name: infra-workflow

on:
  push:
    branches: [ main ]

jobs:
  tf-plan:
    name: build-plan
    runs-on: ubuntu-latest
    
    # Inject AWS credentials for provider auth
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1" 

    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-tf-cli
        uses: hashicorp/setup-terraform@v3

      # Initialize backend and fetch providers
      - name: tf-init
        run: terraform init

      # Generate execution plan for review
      - name: tf-plan
        run: terraform plan