name: infra-workflow

on:
  push:
    branches: [ main ]

jobs:
  tf-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1" 

    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-tf-cli
        uses: hashicorp/setup-terraform@v3

      - name: tf-init
        run: terraform init

      - name: tf-plan
        run: terraform plan

      - name: tf-apply
        run: terraform apply -auto-approve